$background = rgba(2D353Bff)
$foreground = rgba(D3C6AAff)
$surface = rgba(343F44ff)
$on_surface = rgba(D3C6AAff)
$primary = rgba(A7C080ff)
$on_primary = rgba(2D353Bff)
$inverse_primary = rgba(83C092ff)
$tertiary = rgba(7FBBB3ff)
$error = rgba(E67E80ff)
$warning = rgba(DBBC7Fff)
$success = rgba(A7C080ff)

$hover = rgba(E69875ff)
$selected = rgba(543A48ff)
$surface_alpha = rgba(343F4480)
