$background = rgba(1a1b26ff)
$foreground = rgba(c0caf5ff)
$surface = rgba(24283bff)
$on_surface = rgba(c0caf5ff)
$primary = rgba(7aa2f7ff)
$on_primary = rgba(16161eff)
$inverse_primary = rgba(bb9af7ff)
$tertiary = rgba(7dcffff)
$error = rgba(f7768eff)
$warning = rgba(e0af68ff)
$success = rgba(9ece6aff)

$hover = rgba(292e42ff)
$selected = rgba(33467cff)
$surface_alpha = rgba(24283b80)
