$background = rgba(282828ff)
$foreground = rgba(ebdbb2ff)
$surface = rgba(3c3836ff)
$on_surface = rgba(ebdbb2ff)
$primary = rgba(83a598ff)
$on_primary = rgba(282828ff)
$inverse_primary = rgba(d3869bff)
$tertiary = rgba(8ec07cff)
$error = rgba(fb4934ff)
$warning = rgba(fabd2fff)
$success = rgba(b8bb26ff)

$hover = rgba(fe8019ff)
$selected = rgba(665c54ff)
$surface_alpha = rgba(3c383680)
