[colors-dark]
# GruvBox Theme
background=282828
foreground=ebdbb2

# Selection and Cursor
selection-background=282828
selection-foreground=d4be98
cursor=a89984 d4be98
urls=458588

# Normal Colors (color palette 0-7)
regular0=665c54  # black
regular1=ea6962  # red
regular2=a9b665  # green
regular3=e78a4e  # yellow
regular4=7daea3  # blue
regular5=d3869b  # magenta
regular6=89b482  # cyan
regular7=d4be98  # white

# Bright Colors (color palette 8-15)
bright0=928374   # bright black
bright1=ea6962   # bright red
bright2=a9b665   # bright green
bright3=d8a657   # bright yellow
bright4=7daea3   # bright blue
bright5=d3869b   # bright magenta
bright6=89b482   # bright cyan
bright7=d4be98   # bright white
