font_family JetBrainsMono Nerd Font
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto

modify_font cell_height 110% # Line height
background_opacity 0.85
cursor_shape block

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

# Window
window_padding_width 4
# window_padding_height 4
confirm_os_window_close 0
show_window_riseze_notification no
clipboard_control write-clipboard write-primary read-clipboard read-primary

include current-theme.conf
