set -g status-position top
set -g status-left-length 100

set -g status-style "fg=lightblue,bg=default"
set -g status-left "#{?client_prefix,#[fg=red] ,#[fg=green] } #[fg=green]#S #[fg=lightblue,nobold]| "
set -g status-right ""

set -g window-status-current-format "#[fg=blue,bold] #[underscore]#I:#W"
set -g window-status-format "#I:#W"

set -g message-style "fg=lightblue,bg=default"
set -g mode-style "fg=black,bg=lightblue,bold"

set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=cyan"
