source-file ~/.config/tmux/repo/min-status-bar.conf

# set -ga terminal-overrides ",*:RGB"
# set -g mouse on
set -g set-clipboard on

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# unbind r
# bind r source-file $HOME/.config/tmux/tmux.conf

set-option -g renumber-windows on

# Vim like copy/paste
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel 'xclip -in -selection clipboard'
unbind -T copy-mode-vi MouseDragEnd1Pane

# Ctrl+hjkl to switch panes (vim-style)
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Alt+number to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# Sessionizer
bind-key -n C-f run-shell "tmux neww tmux-sessionizer"
